on: [push]

jobs:
  upload_files:
    runs-on: ubuntu-latest
    name: Deploy latest version
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Upload Files
        id: upload
        uses: Creepios/sftp-action@v1.0.3
        with:
          host: '${{ secrets.DEPLOY_HOST }}'
          port: 22
          username: '${{ secrets.DEPLOY_USERNAME }}'
          privateKey: '${{ secrets.DEPLOY_KEY }}'
          localPath: './'
          remotePath: '${{ secrets.DEPLOY_PATH }}'